"""Empirical firmware oracle index loader and verdict resolver for OpenWebNet frames.

Loads results/mcp_index.json generated by own-firmware-oracle, which records exact
client session responses, bus telegram emissions, and SHA-256 provenance from
live QEMU firmware execution on BTicino MH200N and MyHomeServer1 gateways.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

from openwebnet_mcp._paths import get_oracle_index_path

logger = logging.getLogger("openwebnet_mcp.firmware_oracle")


def normalize_frame(frame: str) -> str:
    """Normalize OpenWebNet frame string for dictionary lookup."""
    f = frame.strip()
    if f and not f.startswith("*"):
        f = "*" + f
    if f and not f.endswith("##"):
        f = f + "##"
    return f


class FirmwareOracle:
    """In-memory loader and query engine for empirical firmware execution verdicts."""

    def __init__(self, index_path: Path | None = None) -> None:
        self.explicit_path = index_path
        self.path: Path | None = None
        self.loaded: bool = False
        self.load_error: str | None = None
        self.generator: str | None = None
        self.format_version: str | None = None
        self.schema_version: str | None = None
        self.total_unique_inputs: int = 0
        self.gateways: list[dict[str, Any]] = []
        self.verdicts: dict[str, list[dict[str, Any]]] = {}

    def load(self) -> bool:
        """Load or reload the oracle index from disk. Returns True on success."""
        resolved = self.explicit_path or get_oracle_index_path()
        if not resolved or not resolved.is_file():
            self.loaded = False
            self.load_error = f"Oracle index not found (resolved: {resolved})"
            logger.debug(self.load_error)
            return False

        self.path = resolved
        try:
            with open(resolved, "r", encoding="utf-8") as f:
                data = json.load(f)

            self.generator = data.get("generator")
            self.format_version = data.get("format_version")
            self.schema_version = data.get("schema_version")
            self.total_unique_inputs = int(data.get("total_unique_inputs", 0))
            self.gateways = data.get("gateways", [])
            self.verdicts = data.get("verdicts", {})
            self.loaded = True
            self.load_error = None
            logger.info(
                "Loaded firmware oracle index from %s (%d inputs, %d gateways)",
                resolved,
                len(self.verdicts),
                len(self.gateways),
            )
            return True
        except Exception as err:
            self.loaded = False
            self.load_error = f"Failed to parse oracle index {resolved}: {err}"
            logger.warning(self.load_error, exc_info=True)
            return False

    def reload(self) -> bool:
        """Force reload from disk."""
        return self.load()

    def lookup(self, frame: str) -> list[dict[str, Any]] | None:
        """Look up empirical verdicts for an OpenWebNet frame.

        Returns a list of verdict dicts across tested gateways, or None if not indexed.
        """
        if not self.loaded:
            self.load()

        if not self.loaded:
            return None

        # Try exact string
        if frame in self.verdicts:
            return self.verdicts[frame]

        # Try normalized
        norm = normalize_frame(frame)
        if norm in self.verdicts:
            return self.verdicts[norm]

        return None

    def format_verdict_markdown(
        self,
        frame: str,
        verdicts: list[dict[str, Any]] | None,
    ) -> str:
        """Format empirical verdicts into a GitHub-flavored Markdown section."""
        norm = normalize_frame(frame)
        if not verdicts:
            return (
                "## 🛡️ Empirical Firmware Oracle Verification\n"
                f"*Frame `{norm}` has not yet been replayed against firmware test suites "
                "(MyHomeServer1 / MH200N).*"
            )

        lines = [
            f"## 🛡️ Empirical Firmware Oracle Verification: `{norm}`",
            "",
            "| Gateway | Firmware | Reply | Verdict | Bus Frames Emitted | Emitted OWN | Suite | Target SHA |",
            "|---|---|---|---|---|---|---|---|",
        ]

        for v in verdicts:
            gw = v.get("product", "Unknown")
            ver = v.get("version", "Unknown")
            raw_reply = v.get("reply", "silent").lower()
            if raw_reply == "ack":
                reply = "`ACK (*#*1##)`"
            elif raw_reply == "nack":
                reply = "`NACK (*#*0##)`"
            elif raw_reply == "silent":
                reply = "`SILENT`"
            else:
                reply = f"`{raw_reply}`"

            verdict_badge = f"`{v.get('verdict', 'unknown')}`"

            bus = v.get("bus_frames") or []
            bus_str = f"`{', '.join(bus)}`" if bus else "*(none)*"

            emitted = v.get("emitted_own") or []
            emitted_str = f"`{', '.join(emitted)}`" if emitted else "*(none)*"

            suite = v.get("suite", "unknown")
            target_sha = (v.get("target_sha256") or "")[:12]
            sha_str = f"`{target_sha}`" if target_sha else "*(n/a)*"

            lines.append(
                f"| **{gw}** | `{ver}` | {reply} | {verdict_badge} | {bus_str} | {emitted_str} | `{suite}` | {sha_str} |"
            )

        lines.extend([
            "",
            "### 🔬 Ground Truth Analysis",
        ])

        for v in verdicts:
            gw = v.get("product", "Unknown")
            ver = v.get("version", "Unknown")
            reply = v.get("reply", "silent")
            bus = v.get("bus_frames") or []
            emitted = v.get("emitted_own") or []
            suite = v.get("suite", "unknown")
            src = v.get("source_tsv", "")

            details = [f"- **{gw} ({ver})**:"]
            if reply.lower() == "ack":
                details.append("Gateway acknowledged the command (`*#*1##`).")
            elif reply.lower() == "nack":
                details.append("Gateway refused/rejected the command (`*#*0##`).")
            else:
                details.append(f"Gateway returned: `{reply}`.")

            if bus:
                details.append(f"Dispatched {len(bus)} SCS bus telegram(s): `{', '.join(bus)}`.")
            else:
                details.append("No SCS bus telegrams emitted.")

            if emitted:
                details.append(f"Emitted session responses: `{', '.join(emitted)}`.")

            if src:
                details.append(f"Provenance: suite `{suite}` in `{src}`.")

            lines.append(" ".join(details))

        return "\n".join(lines)

    def status(self) -> dict[str, Any]:
        """Return diagnostic status information."""
        if not self.loaded:
            self.load()

        return {
            "loaded": self.loaded,
            "path": str(self.path) if self.path else None,
            "generator": self.generator,
            "format_version": self.format_version,
            "schema_version": self.schema_version,
            "total_unique_inputs": self.total_unique_inputs,
            "total_verdicts": len(self.verdicts),
            "gateways": [
                {
                    "product": g.get("product"),
                    "version": g.get("version"),
                    "suites_count": len(g.get("suites", [])),
                }
                for g in self.gateways
            ],
            "load_error": self.load_error,
        }
